import { config } from "dotenv";

config({ path: ".env" });

export const {
  PORT,
  NODE_ENV,
  API_URL,
  API_DESCRIPTION,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  HMAC_SECRET_KEY,
  WHATSAPP_BUSINESS_NUMBER,
  WHATSAPP_BUSINESS_PHONE,
  WHATSAPP_APP_SECRET,
  WHATSAPP_VERIFY_TOKEN,
  WHATSAPP_ACCESS_TOKEN,
  INTERNAL_API_BASE_URL,
} = process.env;
